import React, { useEffect, useMemo, useState } from 'react'
import { Search, Moon, Sun, MapPin, ExternalLink, Share2, Download, Filter, ChevronRight, ShieldCheck, BookOpen, AlertTriangle, Activity, CalendarDays, Menu, X } from 'lucide-react'
import { Button, Badge, Card, CardHeader, CardTitle, CardDescription, Sheet, Progress, EmptyState } from './components/ui.jsx'

const repoBase = import.meta.env.BASE_URL || './'
const json = (p) => fetch(`${repoBase}${p}`.replace(/([^:]\/)\/+/g,'$1')).then(r=>{ if(!r.ok) throw new Error(`${p}: ${r.status}`); return r.json() })
const tone = n => Number(n)>=76?'red':Number(n)>=41?'orange':Number(n)>=26?'yellow':'green'
const toneLabel = n => ({red:'Critical',orange:'High',yellow:'Watch',green:'Low'})[tone(n)]
const esc = (v) => v == null ? '' : String(v)

const cityCoords = {
  Tengger:[-7.942,112.953], Karanganyar:[-7.596,110.951], Banyumas:[-7.515,109.294], 'Barito Utara':[-0.78,114.74],
  Tuban:[-6.897,112.064], Bangka:[-2.15,106.12], Medan:[3.595,98.672], Mempawah:[0.35,108.95],
  'Palangka Raya':[-2.21,113.92], Cibubur:[-6.37,106.88], Dieng:[-7.21,109.92], Trenggalek:[-8.05,111.70], Indonesia:[-2.5,118]
}

function App(){
  const [registry,setRegistry]=useState(null), [month,setMonth]=useState(null), [report,setReport]=useState(null), [issues,setIssues]=useState([]), [evidence,setEvidence]=useState([]), [revelation,setRevelation]=useState(null)
  const [query,setQuery]=useState(''), [filter,setFilter]=useState('all'), [sheet,setSheet]=useState(null), [dark,setDark]=useState(()=>localStorage.getItem('wml-theme')==='dark'), [menu,setMenu]=useState(false), [installPrompt,setInstallPrompt]=useState(null)

  useEffect(()=>{ document.documentElement.classList.toggle('dark',dark); localStorage.setItem('wml-theme',dark?'dark':'light') },[dark])
  useEffect(()=>{
    json('data/index.json').then(r=>{setRegistry(r); const m=r.months?.find(x=>x.id==='2026-08')||r.months?.[0]; setMonth(m)}).catch(()=>{})
    const handler=e=>{e.preventDefault();setInstallPrompt(e)}; window.addEventListener('beforeinstallprompt',handler); return()=>window.removeEventListener('beforeinstallprompt',handler)
  },[])
  useEffect(()=>{ if(!month)return; Promise.all([json(month.path),json(month.issues),json(month.evidence),json(month.revelation)]).then(([a,b,c,d])=>{setReport(a);setIssues(b);setEvidence(c);setRevelation(d)}).catch(()=>{}) },[month])

  const observations = report?.observations || []
  const filtered = useMemo(()=>observations.filter(o=>{
    const q=query.toLowerCase(); const hay=[o.date,o.location,o.actor,o.practice,o.summary].join(' ').toLowerCase();
    return (!q||hay.includes(q)) && (filter==='all'||tone(o.tauhid_gap)===filter)
  }),[observations,query,filter])

  function refFor(o){return o?.revelation_refs || revelation?.default_row_refs || {Q:'112:1–4',I:'Mark 12:29–31',T:'Deut. 6:4–5',Z:'Ps. 86:10'}}
  function openObservation(o){setSheet({kind:'observation',item:o})}
  function openIssue(i){setSheet({kind:'issue',item:i})}
  function openEvidence(i){setSheet({kind:'evidence',item:i})}
  async function install(){ if(!installPrompt)return; await installPrompt.prompt(); setInstallPrompt(null) }
  async function share(){ const data={title:'WHERE MYTH FADE TO LEGEND',text:`${month?.label||'Observatory'} — Indonesia Mythos & Ritual Observatory`,url:location.href}; try{ if(navigator.share) await navigator.share(data); else await navigator.clipboard.writeText(location.href) }catch{} }
  function story(item,kind='Observation'){ const c=document.createElement('canvas'); c.width=1080;c.height=1920;const x=c.getContext('2d'); x.fillStyle=dark?'#0b0b0f':'#f8fafc';x.fillRect(0,0,c.width,c.height);x.fillStyle='#111827'; if(dark)x.fillStyle='#f4f4f5'; x.font='700 28px system-ui';x.fillText('WHERE MYTH FADE TO LEGEND',72,100);x.fillStyle='#6d28d9';x.font='800 64px system-ui';x.fillText(kind.toUpperCase(),72,210);x.fillStyle=dark?'#f4f4f5':'#111827';x.font='800 74px system-ui';wrap(x,esc(item?.practice||item?.issue||item?.title||'August 2026'),72,340,900,86,4);x.font='500 34px system-ui';x.fillStyle=dark?'#c5c7d0':'#4b5563';wrap(x,esc(item?.summary||item?.resolution||item?.description||'Evidence-first observatory snapshot.'),72,700,900,48,8); if(item?.tauhid_gap!=null){x.fillStyle=toneColor(item.tauhid_gap);x.font='800 52px system-ui';x.fillText(`Tauhid Gap ${item.tauhid_gap}/100`,72,1250)} x.fillStyle=dark?'#a1a1aa':'#64748b';x.font='500 26px system-ui';x.fillText(`${month?.label||'August 2026'} · Indonesia`,72,1820);const a=document.createElement('a');a.download='where-myth-fade-story.png';a.href=c.toDataURL('image/png');a.click() }
  const toneColor=n=>tone(n)==='red'?'#c43b49':tone(n)==='orange'?'#bf641f':tone(n)==='yellow'?'#a97800':'#159a70'
  const wrap=(ctx,text,x,y,maxWidth,lineHeight,maxLines)=>{const words=text.split(/\s+/);let line='',lines=0;for(let i=0;i<words.length;i++){const test=line?line+' '+words[i]:words[i];if(ctx.measureText(test).width>maxWidth&&line){ctx.fillText(line,x,y+lines*lineHeight);line=words[i];lines++;if(lines>=maxLines)break}else line=test}if(lines<maxLines)ctx.fillText(line,x,y+lines*lineHeight)}

  if(!report) return <div className="app-loading"><div className="loading-mark">WM</div><p>Loading observatory…</p></div>

  return <div className="app-shell">
    <header className="site-header"><div className="header-inner"><a href="#top" className="brand"><span className="brand-icon">WM</span><span><b>WHERE MYTH FADE TO LEGEND</b><small>INDONESIA OBSERVATORY</small></span></a><nav className={menu?'nav mobile-open':'nav'}>{['dashboard','timeline','observations','issues','evidence','map','revelation'].map((x)=><a key={x} href={`#${x}`} onClick={()=>setMenu(false)}>{x}</a>)}</nav><div className="header-actions"><span className="status"><i/> LIVE</span><select value={month?.id||''} onChange={e=>setMonth(registry.months.find(m=>m.id===e.target.value))}>{(registry?.months||[]).map(m=><option key={m.id} value={m.id}>{m.label}</option>)}</select><Button variant="outline" size="icon" onClick={()=>setDark(v=>!v)} title="Toggle theme">{dark?<Sun size={16}/>:<Moon size={16}/>}</Button><Button variant="outline" size="icon" onClick={()=>setMenu(v=>!v)} className="menu-btn">{menu?<X size={16}/>:<Menu size={16}/>}</Button></div></div></header>

    <main id="top">
      <section className="hero"><div><div className="eyebrow">MONTHLY OBSERVATORY · {month.label.toUpperCase()}</div><h1>Where <span>Myth</span><br/>Fade to Legend</h1><p>Evidence-first monitoring of mythos, ritual, religious context, revelation references, media and causality across Indonesia.</p><div className="hero-actions"><Button onClick={share}><Share2 size={15}/> Share dashboard</Button>{installPrompt&&<Button variant="outline" onClick={install}>Install app</Button>}<Button variant="ghost" onClick={()=>story({title:month.label},'Monthly')}><Download size={15}/> Story</Button></div></div><Card className="hero-summary"><div className="hero-summary-top"><span>BOARD STATUS</span><Badge tone="green">EVIDENCE-LED</Badge></div><strong>August 2026</strong><Progress value={88}/><div className="hero-summary-grid"><span><small>Observations</small><b>{observations.length}</b></span><span><small>Issues</small><b>{issues.length}</b></span><span><small>Evidence</small><b>{evidence.length}</b></span><span><small>Red</small><b>{observations.filter(o=>tone(o.tauhid_gap)==='red').length}</b></span></div></Card></section>

      <section id="dashboard" className="section"><div className="section-heading"><div><div className="eyebrow">01 · LIVE OVERVIEW</div><h2>August at a glance</h2><p>Scores describe specific practices, not religions or people.</p></div></div><div className="kpi-grid">{(report.kpis||[]).map(k=><Card key={k.label}><div className="kpi-label">{k.label}</div><div className="kpi-value">{k.value}</div><div className="kpi-note">{k.note}</div></Card>)}</div></section>

      <section id="timeline" className="section"><div className="section-heading"><div><div className="eyebrow">02 · TIMELINE</div><h2>What happened, when</h2></div><Button variant="outline" onClick={()=>story(null,'Timeline')}><Download size={15}/> Generate Image</Button></div><div className="timeline-grid">{observations.map((o,i)=><button key={i} className="timeline-card" onClick={()=>openObservation(o)}><div className="timeline-top"><span>{o.date}</span><Badge tone={tone(o.tauhid_gap)}>{toneLabel(o.tauhid_gap)}</Badge></div><b>{o.location}</b><strong>{o.practice}</strong><small>Gap {o.tauhid_gap}/100</small></button>)}</div></section>

      <section id="observations" className="section"><div className="section-heading"><div><div className="eyebrow">03 · OBSERVATIONS</div><h2>Live observation board</h2><p>Open a row to inspect evidence, scores, revelation references and source.</p></div><Button variant="outline" onClick={()=>story(null,'Observations')}><Download size={15}/> Generate Image</Button></div><div className="toolbar"><div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search location, ritual, actor…"/></div><div className="filter"><Filter size={15}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All levels</option><option value="red">Critical</option><option value="orange">High</option><option value="yellow">Watch</option><option value="green">Low</option></select></div></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Location</th><th>Practice</th><th>Evidence</th><th>Tauhid Gap</th><th>Causality</th><th>4 Revelation</th><th></th></tr></thead><tbody>{filtered.map((o,i)=><tr key={i}><td>{o.date}</td><td><b>{o.location}</b><div className="muted">{o.actor}</div></td><td><b>{o.practice}</b><div className="muted">{o.summary}</div></td><td><Badge tone={tone(o.evidence_score)}>{o.evidence_score}/100</Badge></td><td><Badge tone={tone(o.tauhid_gap)}>{o.tauhid_gap}/100</Badge></td><td><Badge tone={tone(o.causality)}>{o.causality}/100</Badge></td><td><div className="refs"><span>Q {refFor(o).Q}</span><span>I {refFor(o).I}</span><span>T {refFor(o).T}</span><span>Z {refFor(o).Z}</span></div></td><td><Button size="sm" variant="ghost" onClick={()=>openObservation(o)}>Open <ChevronRight size={14}/></Button></td></tr>)}</tbody></table></div></section>

      <section className="section split"><Card><CardHeader><Badge tone="neutral">TAUHID GAP</Badge><CardTitle>Risk distribution</CardTitle><CardDescription>Current observation set by severity.</CardDescription></CardHeader><div className="bars">{[['green','Low'],['yellow','Watch'],['orange','High'],['red','Critical']].map(([t,l])=>{const count=observations.filter(o=>tone(o.tauhid_gap)===t).length;return <div key={t} className="bar-row"><div><span>{l}</span><b>{count}</b></div><div className="bar"><i className={`bar-${t}`} style={{width:`${Math.max(6,count/Math.max(1,observations.length)*100)}%`}}/></div></div>})}</div></Card><Card><CardHeader><Badge tone="neutral">CAUSALITY</Badge><CardTitle>Ritual → event</CardTitle><CardDescription>Timing is not treated as proof of causation.</CardDescription></CardHeader><div className="causal-list">{(report.causality||[]).map(c=><button key={c.name} onClick={()=>setSheet({kind:'causality',item:c})}><span>{c.name}</span><Badge tone={tone(c.score)}>{c.score}/100</Badge><small>{c.finding}</small></button>)}</div></Card></section>

      <section id="map" className="section"><div className="section-heading"><div><div className="eyebrow">04 · MAP</div><h2>Indonesia observation geography</h2></div><Button variant="outline" onClick={()=>story(null,'Map')}><Download size={15}/> Generate Image</Button></div><div className="map-panel"><div className="map-grid">{observations.map((o,i)=>{const c=cityCoords[o.location]||cityCoords.Indonesia;return <button key={i} className={`map-pin ${tone(o.tauhid_gap)}`} style={{left:`${((c[1]-95)/45)*100}%`,top:`${((6-c[0])/18)*100}%`}} title={`${o.location} · ${o.practice}`} onClick={()=>openObservation(o)}><span>{i+1}</span></button>})}<div className="map-label map-indonesia">INDONESIA</div></div><div className="map-legend"><span><i className="dot green"/> Low</span><span><i className="dot yellow"/> Watch</span><span><i className="dot orange"/> High</span><span><i className="dot red"/> Critical</span><small>Approximate city positions for orientation.</small></div></div></section>

      <section id="revelation" className="section"><div className="section-heading"><div><div className="eyebrow">05 · FOUR REVELATION LENS</div><h2>Reference the question back to God</h2><p>Cross-reference for theological comparison; not a claim that scripture predicts a modern event.</p></div></div><div className="revelation-grid">{(revelation?.traditions||[]).map(r=><Card key={r.key}><Badge tone="neutral">{r.key}</Badge><h3>{r.name}</h3><strong>{r.references.join(' · ')}</strong><p>{r.focus}</p><a href={r.url} target="_blank" rel="noreferrer">Open source <ExternalLink size={13}/></a></Card>)}</div></section>

      <section id="issues" className="section"><div className="section-heading"><div><div className="eyebrow">06 · ISSUE CENTER</div><h2>Resolution queue</h2><p>Evidence → analysis → constructive clarification.</p></div><Button variant="outline" onClick={()=>story(null,'Issues')}><Download size={15}/> Generate Image</Button></div><div className="issue-grid">{issues.map(i=><button key={i.id} className={`issue-card ${tone(i.tauhid_gap||0)}`} onClick={()=>openIssue(i)}><div><Badge tone={i.priority==='CRITICAL'?'red':i.priority==='HIGH'?'orange':'yellow'}>{i.priority}</Badge><span>{i.id}</span></div><strong>{i.issue}</strong><p>{i.target}</p><small>{i.status}</small></button>)}</div></section>

      <section id="evidence" className="section"><div className="section-heading"><div><div className="eyebrow">07 · EVIDENCE</div><h2>Source trail</h2><p>Primary, official and media sources behind the observations.</p></div><Button variant="outline" onClick={()=>story(null,'Evidence')}><Download size={15}/> Generate Image</Button></div><div className="evidence-grid">{evidence.map((e,i)=><Card key={i}><div className="evidence-top"><Badge tone="neutral">{e.source_grade||'SOURCE'}</Badge><small>{e.published||''}</small></div><h3>{e.title}</h3><p>{e.description}</p><div className="card-actions"><Button size="sm" variant="outline" onClick={()=>openEvidence(e)}>View</Button><Button size="sm" variant="ghost" onClick={()=>window.open(e.url,'_blank','noopener,noreferrer')}>Source <ExternalLink size={13}/></Button></div></Card>)}</div></section>

      <section className="section"><Card className="method-card"><div><div className="eyebrow">08 · METHOD</div><h2>Evidence first. Context always.</h2><p>Evidence quality, religious context, revelation references, Tauhid Gap and causality are separate dimensions. Red marks a specific practice requiring attention—not a religion or people.</p></div><div className="method-list"><span><ShieldCheck size={16}/> Evidence</span><span><BookOpen size={16}/> Context</span><span><Activity size={16}/> Causality</span><span><AlertTriangle size={16}/> Issue / Resolution</span></div></Card></section>
    </main>

    <Sheet open={!!sheet} title={sheet?.kind==='observation'?'Observation detail':sheet?.kind==='issue'?'Issue detail':sheet?.kind==='evidence'?'Evidence detail':'Causality detail'} onClose={()=>setSheet(null)}>
      {sheet?.kind==='observation'&&<><div className="detail-badges"><Badge tone={tone(sheet.item.evidence_score)}>Evidence {sheet.item.evidence_score}/100</Badge><Badge tone={tone(sheet.item.tauhid_gap)}>Tauhid Gap {sheet.item.tauhid_gap}/100</Badge><Badge tone={tone(sheet.item.causality)}>Causality {sheet.item.causality}/100</Badge></div><div className="detail-grid"><span><small>Date</small><b>{sheet.item.date}</b></span><span><small>Location</small><b>{sheet.item.location}</b></span><span><small>Actor</small><b>{sheet.item.actor}</b></span><span><small>Practice</small><b>{sheet.item.practice}</b></span></div><div className="detail-copy"><small>Observation</small><p>{sheet.item.summary}</p></div><div className="detail-copy"><small>Four Revelation</small><div className="refs large"><span>Q {refFor(sheet.item).Q}</span><span>I {refFor(sheet.item).I}</span><span>T {refFor(sheet.item).T}</span><span>Z {refFor(sheet.item).Z}</span></div></div><div className="sheet-actions"><Button onClick={()=>story(sheet.item,'Observation')}><Download size={15}/> Generate Story</Button><Button variant="outline" onClick={()=>window.open(sheet.item.source,'_blank','noopener,noreferrer')}>Open source <ExternalLink size={14}/></Button></div></>}
      {sheet?.kind==='issue'&&<><div className="detail-badges"><Badge tone={sheet.item.priority==='CRITICAL'?'red':sheet.item.priority==='HIGH'?'orange':'yellow'}>{sheet.item.priority}</Badge><Badge tone="neutral">{sheet.item.id}</Badge></div><div className="detail-copy"><small>Issue</small><p>{sheet.item.issue}</p></div><div className="detail-grid"><span><small>Target</small><b>{sheet.item.target}</b></span><span><small>Status</small><b>{sheet.item.status}</b></span></div><div className="detail-copy"><small>Resolution</small><p>{sheet.item.resolution}</p></div><Button onClick={()=>story(sheet.item,'Issue')}><Download size={15}/> Generate Story</Button></>}
      {sheet?.kind==='evidence'&&<><div className="detail-copy"><small>Source</small><p>{sheet.item.title}</p></div><div className="detail-copy"><small>Description</small><p>{sheet.item.description}</p></div><div className="detail-grid"><span><small>Grade</small><b>{sheet.item.source_grade||'—'}</b></span><span><small>Published</small><b>{sheet.item.published||'—'}</b></span></div><div className="sheet-actions"><Button onClick={()=>window.open(sheet.item.url,'_blank','noopener,noreferrer')}>Open source <ExternalLink size={14}/></Button><Button variant="outline" onClick={()=>story(sheet.item,'Evidence')}><Download size={15}/> Generate Story</Button></div></>}
      {sheet?.kind==='causality'&&<><div className="detail-badges"><Badge tone={tone(sheet.item.score)}>Causality {sheet.item.score}/100</Badge></div><div className="detail-copy"><small>Relationship</small><p>{sheet.item.name}</p></div><div className="detail-copy"><small>Finding</small><p>{sheet.item.finding}</p></div></>}
    </Sheet>

    <footer className="footer"><b>WHERE MYTH FADE TO LEGEND</b><span>Monthly observatory · August 2026 · Evidence-first · Mobile-first · Firm on Tauhid</span></footer>
  </div>
}

export default App
