import React, { useEffect, useMemo, useState } from "react"
import { Activity, ArrowUpRight, BookOpen, CircleAlert, Compass, Download, ExternalLink, Eye, FileSearch, Flame, Globe2, Menu, Moon, Radio, Search, ShieldCheck, Sparkles, Sun, Target, X } from "lucide-react"

const base=(import.meta.env.BASE_URL||"/").replace(/\/+$/ ,"")
const get=async p=>{const r=await fetch(`${base}/${p}`.replace(/([^:]\/)\/+/g,"$1"));if(!r.ok)throw Error(`${p}: ${r.status}`);return r.json()}
const NAV=[["home","Home",Moon],["observatory","Observatory",Eye],["mythos","Mythos",Target],["rituals","Ritual Watch",Activity],["revelation","Revelation",BookOpen],["media","Media Watch",Radio],["causality","Causality",Compass]]
const risk=v=>Number(v)>=76?"critical":Number(v)>=41?"high":Number(v)>=26?"watch":"low"
const label=v=>({critical:"Critical",high:"High",watch:"Watch",low:"Low"})[risk(v)]
const Score=({v})=><span className={`score ${risk(v)}`}><i/> {v}/100 · {label(v)}</span>

export default function App(){
 const [registry,setRegistry]=useState({months:[]}),[month,setMonth]=useState(null),[report,setReport]=useState(null),[issues,setIssues]=useState([]),[evidence,setEvidence]=useState([]),[revelation,setRevelation]=useState({traditions:[]}),[monitor,setMonitor]=useState(null),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[drawer,setDrawer]=useState(null),[mobile,setMobile]=useState(false),[dark,setDark]=useState(()=>localStorage.getItem("mw-theme")!=="light"),[route,setRoute]=useState(()=>location.hash.slice(1)||"home")
 useEffect(()=>{const f=()=>setRoute(location.hash.slice(1)||"home");addEventListener("hashchange",f);return()=>removeEventListener("hashchange",f)},[])
 useEffect(()=>{document.documentElement.classList.toggle("dark",dark);localStorage.setItem("mw-theme",dark?"dark":"light")},[dark])
 useEffect(()=>{get("data/index.json").then(d=>{setRegistry(d);setMonth(d.months?.find(x=>x.id==="2026-08")||d.months?.find(x=>x.status==="final")||d.months?.[0])}).catch(()=>{})},[])
 useEffect(()=>{if(!month)return;Promise.all([get(month.path),get(month.issues),get(month.evidence),get(month.revelation)]).then(([a,b,c,d])=>{setReport(a);setIssues(b);setEvidence(c);setRevelation(d)}).catch(()=>{})},[month])
 useEffect(()=>{get("data/monitor/latest.json").then(setMonitor).catch(()=>{});const t=setInterval(()=>get("data/monitor/latest.json").then(setMonitor).catch(()=>{}),300000);return()=>clearInterval(t)},[])
 const obs=report?.observations||[]
 const filtered=useMemo(()=>obs.filter(x=>{const h=[x.date,x.location,x.actor,x.practice,x.summary].join(" ").toLowerCase();return(!query||h.includes(query.toLowerCase()))&&(filter==="all"||risk(x.tauhid_gap)===filter)}),[obs,query,filter])
 const go=n=>{setMobile(false);location.hash=n}
 const open=(kind,item)=>setDrawer({kind,item})
 const download=()=>{const text=["MOONWITNESS — WHERE MYTH FADES TO LEGEND",`${month?.label||"Observatory"} · ${report?.scope||"Indonesia"}`,"","OBSERVE. VERIFY. CLARIFY. PURIFY.","Evidence before amplification.","",...obs.map(x=>`${x.date} | ${x.location} | ${x.practice} | Evidence ${x.evidence_score}/100 | Tauhid Gap ${x.tauhid_gap}/100`)].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/plain"}));a.download="moonwitness-august-2026-brief.txt";a.click()}
 if(!report)return <div className="app-shell loading-shell"><div className="loading-orbit"><Moon size={28}/><span>Synchronizing Observatory…</span></div></div>
 return <div className="app-shell"><aside className={`side-rail ${mobile?"mobile-open":""}`}><button className="brand" onClick={()=>go("home")}><span className="brand-mark"><Moon size={18}/></span><span><strong>MOONWITNESS</strong><em>WHERE MYTH FADES TO LEGEND</em></span></button><div className="rail-rule"/><nav className="rail-nav">{NAV.map(([k,n,I])=><button key={k} className={route===k?"active":""} onClick={()=>go(k)}><I size={16}/><span>{n}</span></button>)}</nav><div className="rail-bottom"><div className="signal"><span className="signal-dot"/> SYSTEM ONLINE <small>{monitor?.updated_at||"LIVE"}</small></div><button className="theme-button" onClick={()=>setDark(x=>!x)}>{dark?<Sun size={16}/>:<Moon size={16}/>} {dark?"Light":"Dark"} mode</button></div></aside>{mobile&&<button className="mobile-scrim" onClick={()=>setMobile(false)}/>}<main className="main-canvas"><header className="topbar"><button className="mobile-menu" onClick={()=>setMobile(x=>!x)}>{mobile?<X/>:<Menu/>}</button><div className="crumb"><span>MONTHLY OBSERVATORY</span><i>/</i><strong>{month?.label||"AUGUST 2026"}</strong></div><div className="top-actions"><select value={month?.id||""} onChange={e=>setMonth(registry.months.find(x=>x.id===e.target.value))}>{registry.months.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><button className="icon-button" onClick={download}><Download size={16}/></button><div className="live-chip"><span/> LIVE</div></div></header>{route==="home"&&<Home report={report} obs={obs} evidence={evidence} issues={issues} go={go}/>} {route==="observatory"&&<Observatory report={report} obs={obs} open={open}/>} {route==="mythos"&&<Mythos filtered={filtered} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} open={open}/>} {route==="rituals"&&<Ritual obs={obs} open={open}/>} {route==="revelation"&&<Revelation revelation={revelation} obs={obs}/>} {route==="media"&&<Media evidence={evidence}/>} {route==="causality"&&<Causality report={report} obs={obs}/>}<footer className="footer"><div><strong>MOONWITNESS</strong><span>Evidence before amplification.</span></div><div className="footer-doctrine">OBSERVE · VERIFY · CLARIFY · PURIFY</div><div className="footer-note">Specific practices, claims and sources — not communities.</div></footer></main>{drawer&&<Drawer drawer={drawer} close={()=>setDrawer(null)}/>}</div>
}

const Frame=({eyebrow,title,description,children})=><section className="page"><div className="page-heading"><div className="eyebrow accent">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{children}</section>
const Head=({eyebrow,title,description,action})=><div className="section-head"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2>{description&&<p>{description}</p>}</div>{action}</div>
const Preview=({x})=><article className="preview-card"><div className="card-top"><span>{x.date}</span><Score v={x.tauhid_gap}/></div><h3>{x.practice}</h3><p>{x.summary}</p><span>{x.location}</span></article>

function Home({report,obs,evidence,issues,go}){const critical=obs.filter(x=>risk(x.tauhid_gap)==="critical").length;return <><section className="hero-panel"><div className="star-field"/><div className="hero-copy"><div className="eyebrow accent">MONTHLY OBSERVATORY · AUGUST 2026</div><h1>Where <span>Myth</span><br/>Fades to Legend</h1><p>Evidence-first monitoring of mythos, ritual, religious context, revelation references, media and causality across Indonesia.</p><div className="hero-actions"><button className="primary" onClick={()=>go("observatory")}>Enter Observatory <ArrowUpRight size={16}/></button><button className="secondary" onClick={()=>go("revelation")}>Open Revelation Index <BookOpen size={16}/></button></div><div className="hero-meta"><span><ShieldCheck size={15}/> Evidence-first</span><span><Globe2 size={15}/> Indonesia</span><span><CircleAlert size={15}/> Contextual scoring</span></div></div><div className="moon-stage"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="moon-core"><div className="crater c1"/><div className="crater c2"/><div className="crater c3"/><div className="moon-crosshair"/></div><div className="radar-ring"/></div><div className="hero-label">TRUTH / CLAIM / EVIDENCE<br/><b>OBSERVATORY NODE 01</b></div></section><section className="stat-strip">{[["Observations",obs.length,"field records"],["Evidence",evidence.length,"source items"],["Issues",issues.length,"review queue"],["Critical",critical,"high tauhid-gap signals"]].map(([a,b,c])=><div className="stat-card" key={a}><span>{a}</span><strong>{b.toLocaleString()}</strong><small>{c}</small></div>)}</section><section className="mission-grid">{[[Eye,"01 · OBSERVE","See the pattern before naming it.","Map narratives, rituals and media signals without turning assumptions into facts."],[FileSearch,"02 · VERIFY","Follow the source chain.","Separate observation, claim, evidence and interpretation."],[BookOpen,"03 · CLARIFY","Compare revelation references.","Keep textual references visible beside contemporary narratives."],[Sparkles,"04 · PURIFY","Remove the myth from the claim.","Expose unsupported certainty without degrading the people being observed."]].map(([I,e,t,p])=><div className="mission-card" key={e}><div className="mission-icon"><I size={20}/></div><div><div className="eyebrow">{e}</div><h3>{t}</h3><p>{p}</p></div></div>)}</section><section className="quote-band"><div className="quote-mark">◐</div><p>“Evidence before amplification. Context before conclusion.”</p><span>MOONWITNESS FIELD DOCTRINE</span></section><section className="home-preview"><Head eyebrow="LIVE FIELD" title="What the observatory is watching" description="The current month becomes a navigable evidence surface." action={<button className="text-button" onClick={()=>go("mythos")}>Open Mythos Index <ArrowUpRight size={14}/></button>}/><div className="preview-grid">{obs.slice(0,4).map((x,i)=><Preview x={x} key={i}/>)}</div></section></>}

function Observatory({report,obs,open}){const gs=["low","watch","high","critical"].map(k=>({k,n:obs.filter(x=>risk(x.tauhid_gap)===k).length}));const max=Math.max(1,...gs.map(x=>x.n));return <Frame eyebrow="02 · COMMAND CENTER" title="Observatory" description="A field command view for the August 2026 evidence board."><div className="dashboard-grid"><div className="panel wide"><div className="panel-head"><div><span>TAUHID GAP DISTRIBUTION</span><small>Severity across observed practices</small></div><Target size={18}/></div><div className="bar-chart">{gs.map(x=><div className="bar-row" key={x.k}><div className={`bar-value ${x.k}`}>{x.n}</div><div className="bar-track"><div className={`bar-fill ${x.k}`} style={{height:`${Math.max(10,x.n/max*100)}%`}}/></div><span>{x.k}</span></div>)}</div></div><div className="panel"><div className="panel-head"><div><span>FIELD STATUS</span><small>{report.period||"AUGUST 2026"}</small></div><Activity size={18}/></div><div className="status-stack"><div><strong>{obs.length}</strong><span>observations</span></div><div><strong>{report.scope||"Indonesia"}</strong><span>coverage</span></div><div><strong>LIVE</strong><span>monitor loop</span></div></div></div></div><div className="panel table-panel"><div className="panel-head"><div><span>RECENT OBSERVATIONS</span><small>Click a row to inspect the source context.</small></div><span className="table-count">{obs.length} records</span></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Location</th><th>Practice</th><th>Evidence</th><th>Tauhid Gap</th><th/></tr></thead><tbody>{obs.map((x,i)=><tr key={i}><td>{x.date}</td><td>{x.location}</td><td><b>{x.practice}</b><small>{x.actor}</small></td><td>{x.evidence_score}/100</td><td><Score v={x.tauhid_gap}/></td><td><button className="row-open" onClick={()=>open("observation",x)}>Inspect <ArrowUpRight size={13}/></button></td></tr>)}</tbody></table></div></div></Frame>}

function Mythos({filtered,query,setQuery,filter,setFilter,open}){return <Frame eyebrow="03 · MYTHOS INDEX" title="Mythos" description="Treat the narrative as an object of inquiry — not as proof."><div className="toolbar"><div className="search-box"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search place, actor, practice…"/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All levels</option><option value="critical">Critical</option><option value="high">High</option><option value="watch">Watch</option><option value="low">Low</option></select></div><div className="myth-grid">{filtered.map((x,i)=><article className="myth-card" key={i} onClick={()=>open("observation",x)}><div className="card-top"><span>{x.date}</span><Score v={x.tauhid_gap}/></div><div className="myth-glyph"><Flame size={18}/></div><h3>{x.practice}</h3><p>{x.summary}</p><div className="myth-footer"><span>{x.location}</span><span>Evidence {x.evidence_score}/100</span></div></article>)}</div>{!filtered.length&&<div className="empty-state">No observations match this filter.</div>}<div className="method-note"><ShieldCheck size={18}/><div><strong>Scoring boundary</strong><p>Scores describe the observed practice and evidence chain. They are not verdicts about religions, ethnicities or communities.</p></div></div></Frame>}

function Ritual({obs,open}){return <Frame eyebrow="04 · RITUAL WATCH" title="Ritual Watch" description="Observe practices in context: who, where, what is claimed, and what sources support it."><div className="ritual-layout"><div className="timeline-rail">{obs.map((x,i)=><button key={i} onClick={()=>open("observation",x)}><span>{x.date}</span><i className={`timeline-dot ${risk(x.tauhid_gap)}`}/><div><b>{x.practice}</b><small>{x.location} · {x.actor}</small></div></button>)}</div><div className="ritual-map"><div className="map-grid"/><div className="map-title">INDONESIA / FIELD SIGNAL MAP</div>{obs.slice(0,8).map((x,i)=><button className={`map-point p${i+1}`} key={i} onClick={()=>open("observation",x)}><span/><b>{x.location}</b></button>)}<div className="map-legend"><span><i className="dot low"/> low</span><span><i className="dot watch"/> watch</span><span><i className="dot high"/> high</span><span><i className="dot critical"/> critical</span></div></div></div></Frame>}

function Revelation({revelation,obs}){return <Frame eyebrow="05 · REVELATION INDEX" title="Revelation" description="Cross-reference claims against textual references without collapsing context into a slogan."><div className="revelation-grid">{(revelation?.traditions||[]).map(x=><article className="revelation-card" key={x.key}><div className="revelation-key">{x.key}</div><div><span className="eyebrow">{x.name}</span><h3>{(x.references||[]).join(" · ")}</h3><p>{x.focus}</p></div>{x.url&&<a href={x.url} target="_blank" rel="noreferrer">Open reference <ExternalLink size={13}/></a>}</article>)}</div><div className="panel evidence-panel"><div className="panel-head"><div><span>REFERENCE SNAPSHOT</span><small>Textual context attached to observed entries.</small></div><BookOpen size={18}/></div><div className="reference-list">{obs.slice(0,8).map((x,i)=><div key={i}><div><b>{x.practice}</b><small>{x.location}</small></div><span>Q · {x.revelation_refs?.Q||"112:1–4"}</span><span>I · {x.revelation_refs?.I||"Mark 12:29–31"}</span><span>T · {x.revelation_refs?.T||"Deut. 6:4–5"}</span><span>Z · {x.revelation_refs?.Z||"Ps. 86:10"}</span></div>)}</div></div></Frame>}

function Media({evidence}){return <Frame eyebrow="06 · MEDIA WATCH" title="Media Watch" description="Trace how narratives move through media, sources and repeated claims."><div className="media-layout"><div className="panel media-list"><div className="panel-head"><div><span>RECENT MEDIA EVIDENCE</span><small>Evidence entries from the current month.</small></div><Radio size={18}/></div>{evidence.map((x,i)=><div className="media-item" key={i}><div className="media-icon"><Radio size={15}/></div><div><b>{x.title}</b><p>{x.description}</p><small>{x.source_grade||"Evidence"} · {x.published||"Undated"}</small></div>{x.url&&<a href={x.url} target="_blank" rel="noreferrer"><ExternalLink size={14}/></a>}</div>)}</div><div className="media-radar panel"><div className="panel-head"><div><span>NARRATIVE PROPAGATION</span><small>Source → narrative → propagation → impact</small></div><Sparkles size={18}/></div><div className="radar"><div className="radar-circle r1"/><div className="radar-circle r2"/><div className="radar-circle r3"/><div className="radar-sweep"/><div className="radar-core"><span>{evidence.length}</span><small>items</small></div></div></div></div></Frame>}

function Causality({report,obs}){return <Frame eyebrow="07 · CAUSALITY MAP" title="Causality" description="Track the path from narrative to practice to observed impact."><div className="causal-flow">{[[Sparkles,"MYTH / CLAIM"],[Eye,"BELIEF"],[Activity,"RITUAL"],[Target,"BEHAVIOR"],[Flame,"IMPACT"]].map(([I,t],i)=><React.Fragment key={t}><div className="causal-node"><I size={18}/><span>{t}</span></div>{i<4&&<div className="flow-line"/>}</React.Fragment>)}</div><div className="causal-grid">{(report.causality||[]).map((x,i)=><article className="causal-card" key={i}><div className="causal-score">{x.score}/100</div><div><span className="eyebrow">IMPACT SIGNAL</span><h3>{x.name}</h3><p>{x.finding}</p></div></article>)}</div><div className="causal-table panel"><div className="panel-head"><div><span>FIELD LINKAGE</span><small>Observation and impact paired in one evidence surface.</small></div><Globe2 size={18}/></div><div className="table-wrap"><table><thead><tr><th>Practice</th><th>Location</th><th>Tauhid Gap</th><th>Causality</th><th>Evidence</th></tr></thead><tbody>{obs.map((x,i)=><tr key={i}><td><b>{x.practice}</b></td><td>{x.location}</td><td><Score v={x.tauhid_gap}/></td><td>{x.causality}/100</td><td>{x.evidence_score}/100</td></tr>)}</tbody></table></div></div></Frame>}

function Drawer({drawer,close}){const x=drawer.item||{};return <div className="drawer-scrim" onClick={close}><aside className="detail-drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><span className="eyebrow">{drawer.kind==="observation"?"FIELD OBSERVATION":"EVIDENCE ITEM"}</span><h2>{x.practice||x.title||x.id||"Detail"}</h2></div><button className="icon-button" onClick={close}><X size={17}/></button></div><div className="drawer-body"><div className="score-grid"><div><small>Evidence</small><b>{x.evidence_score??"—"}/100</b></div><div><small>Tauhid Gap</small><b>{x.tauhid_gap??"—"}/100</b></div><div><small>Causality</small><b>{x.causality??"—"}/100</b></div></div><div className="detail-section"><span>Date / Location</span><strong>{x.date||"—"} · {x.location||"—"}</strong></div><div className="detail-section"><span>Community / Actor</span><strong>{x.actor||x.target||"—"}</strong></div><div className="detail-section"><span>Observation / Description</span><p>{x.summary||x.description||x.issue||"No description available."}</p></div>{x.revelation_refs&&<div className="detail-section"><span>Four-revelation reference surface</span><div className="mini-refs"><span>Q · {x.revelation_refs.Q}</span><span>I · {x.revelation_refs.I}</span><span>T · {x.revelation_refs.T}</span><span>Z · {x.revelation_refs.Z}</span></div></div>}{(x.source||x.url)&&<a className="primary full" href={x.source||x.url} target="_blank" rel="noreferrer">Open source <ExternalLink size={14}/></a>}</div></aside></div>}
