import './fasttrack.css'

const base=(import.meta.env.BASE_URL||'/').replace(/\/+$/,'')
const get=async p=>{const r=await fetch(`${base}/${p}`.replace(/([^:]\/)\/+/g,'$1'));if(!r.ok)throw Error(p);return r.json()}
let data=null
const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))
const risk=v=>Number(v)>=76?'critical':Number(v)>=41?'high':Number(v)>=26?'watch':'low'
const nav=[['reports','Reports','▦'],['evidence','Evidence Explorer','⌕'],['about','Methodology','◈']]
function mount(){let el=document.getElementById('mw-fasttrack');if(!el){el=document.createElement('section');el.id='mw-fasttrack';document.querySelector('.main-canvas')?.appendChild(el)}return el}
function addNav(){const n=document.querySelector('.rail-nav');if(!n)return;for(const [key,label,icon] of nav){let b=n.querySelector(`[data-mw-route="${key}"]`);if(!b){b=document.createElement('button');b.className='mw-nav-extra';b.dataset.mwRoute=key;b.innerHTML=`<span style="font-size:15px;width:16px;text-align:center">${icon}</span><span>${label}</span>`;b.onclick=()=>location.hash=key;n.appendChild(b)}b.classList.toggle('active',location.hash.slice(1)===key)}}
function render(){const route=location.hash.slice(1)||'home';const root=document.getElementById('root');const special=nav.some(x=>x[0]===route);const el=mount();if(!special){root.style.display='';el.classList.remove('active');return}root.style.display='none';el.classList.add('active');if(!data){el.innerHTML='<div class="mw-card"><div class="mw-kicker">MONTHLY OBSERVATORY</div><h1>Synchronizing…</h1></div>';return}const {report,evidence,issues}=data;if(route==='reports')renderReports(el,report,issues,evidence);if(route==='evidence')renderEvidence(el,evidence)}
function flowNav(){return `<div class="mw-flow"><span class="current">01 · EVIDENCE</span><span>→</span><button onclick="window.location.hash='analysis'">02 · ANALYSIS</button><span>→</span><button onclick="window.location.hash='resolution'">03 · RESOLUTION</button></div>`}
function renderReports(el,r,issues,evidence){const obs=r.observations||[];const critical=obs.filter(x=>risk(x.tauhid_gap)==='critical').length;const avg=Math.round(obs.reduce((a,x)=>a+Number(x.evidence_score||0),0)/Math.max(1,obs.length));el.innerHTML=`<div class="mw-hero-art"><div><div class="mw-kicker">MONTHLY OBSERVATORY · ${esc(r.period||'AUGUST 2026')}</div><h1>Monthly<br/>Observatory Report</h1><p>A publication-grade field brief: what was observed, how strongly it is evidenced, where uncertainty remains, and which signals require review.</p><span class="mw-pill">EVIDENCE BEFORE AMPLIFICATION</span></div></div>${flowNav()}<div class="mw-grid"><div class="mw-card"><div class="mw-kicker">OBSERVATIONS</div><div class="mw-stat">${obs.length}</div><p>Field records in the current reporting period.</p></div><div class="mw-card"><div class="mw-kicker">EVIDENCE QUALITY</div><div class="mw-stat">${avg}/100</div><p>Mean evidence score across observations.</p></div><div class="mw-card"><div class="mw-kicker">CRITICAL SIGNALS</div><div class="mw-stat">${critical}</div><p>High tauhid-gap records requiring contextual review.</p></div></div><div class="mw-card" style="margin-top:12px"><div class="mw-kicker">FIELD REGISTER</div><table class="mw-table"><thead><tr><th>DATE</th><th>LOCATION</th><th>PRACTICE</th><th>EVIDENCE</th><th>GAP</th></tr></thead><tbody>${obs.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.location)}</td><td>${esc(x.practice)}</td><td>${esc(x.evidence_score)}/100</td><td><span class="mw-pill">${esc(risk(x.tauhid_gap))} · ${esc(x.tauhid_gap)}/100</span></td></tr>`).join('')}</tbody></table></div><div class="mw-grid"><div class="mw-card"><div class="mw-kicker">ISSUE QUEUE</div><div class="mw-stat">${issues.length}</div><p>Open review items connected to the report.</p></div><div class="mw-card"><div class="mw-kicker">SOURCE SURFACE</div><div class="mw-stat">${evidence.length}</div><p>Evidence items available for trace-back.</p></div><div class="mw-card"><div class="mw-kicker">SCOPE</div><div class="mw-stat" style="font-size:25px">${esc(r.scope||'Indonesia')}</div><p>Geographic scope of this report.</p></div></div>`}
function renderEvidence(el,evidence){el.innerHTML=`<div class="mw-kicker">EVIDENCE SYSTEM · TRACEABILITY</div><h1 style="font-family:var(--serif);font-size:64px;font-weight:500;margin:8px 0">Evidence Explorer</h1><p style="color:var(--muted);max-width:700px;line-height:1.8">Inspect the source layer behind the monthly field surface, then move explicitly into analysis.</p>${flowNav()}<div class="mw-card" style="margin-top:12px"><table class="mw-table"><thead><tr><th>SOURCE</th><th>DESCRIPTION</th><th>GRADE</th><th>DATE</th><th>LINK</th></tr></thead><tbody>${evidence.map((x,i)=>`<tr><td><b>${esc(x.title||x.id||`Evidence ${i+1}`)}</b></td><td>${esc(x.description||x.summary||'')}</td><td><span class="mw-pill">${esc(x.source_grade||'Evidence')}</span></td><td>${esc(x.published||'Undated')}</td><td>${x.url?`<a href="${esc(x.url)}" target="_blank" rel="noreferrer">Open ↗</a>`:'—'}</td></tr>`).join('')}</tbody></table></div>`}
function renderAbout(el){el.innerHTML=`<div class="mw-hero-art"><div><div class="mw-kicker">MOONWITNESS · METHOD</div><h1>Observe.<br/>Verify.<br/>Clarify.<br/>Purify.</h1><p>The observatory separates what happened, what is claimed, what supports the claim, and what remains interpretation.</p></div></div><div class="mw-grid"><div class="mw-card"><div class="mw-kicker">01 · OBSERVE</div><h3>Field before theory.</h3><p>Record date, place, actor, practice and description before assigning meaning.</p></div><div class="mw-card"><div class="mw-kicker">02 · VERIFY</div><h3>Source chain first.</h3><p>Evidence items remain visible so a reader can trace a statement back to its source.</p></div><div class="mw-card"><div class="mw-kicker">03 · CLARIFY</div><h3>Context before conclusion.</h3><p>Scores describe observed signals and evidence quality; they are not verdicts about communities.</p></div></div><div class="mw-card" style="margin-top:12px"><div class="mw-kicker">BOUNDARIES</div><ul><li>Specific practices, claims and sources — not communities.</li><li>Uncertainty is preserved rather than converted into certainty.</li><li>Revelation references are presented as textual context, not as a substitute for source criticism.</li><li>Monthly reports are snapshots and should be read with their evidence trail.</li></ul></div>`}
async function boot(){try{data={};const idx=await get('data/index.json');const m=idx.months?.find(x=>x.id==='2026-08')||idx.months?.[0];if(m){[data.report,data.issues,data.evidence]=await Promise.all([get(m.path),get(m.issues),get(m.evidence)])}}catch(e){console.warn('MoonWitness fast-track data',e)}addNav();render();window.addEventListener('hashchange',()=>{setTimeout(()=>{addNav();render()},0)});new MutationObserver(()=>addNav()).observe(document.body,{childList:true,subtree:true})}boot()
